### PR TITLE
Add docstring + usability enhancements

### PR DESCRIPTION
**Pull request by gwerbin**
First of all, thank you for putting this package together. It's much nicer than copying and pasting a recipe out of the documentation.

Changes in this PR:
- Add a docstring for `connect`
- Add `http_path` argument, because HTTP Path can vary across Databricks
  - e.g. the path can have a bunch of digits like `1287361985` instead of just `0` (I had this problem on my Databricks instance at work)
- Use "-name" suffixes in arguments for clarity
  - I know this is a minor point but it can be helpful in an un-typed language like Python, where you might be scratching your head over whether something is a string, or an instance of some class

I still need to run the code through Black for linting and I need to double check that everything works correctly. I just wanted to make sure you're on board with the changes before I put more work in.

### CODE REVIEW

**Comment by crflynn** [comment]
Hi @gwerbin.

Docstring looks good, but you have two ``http_path``s in the signature. Also, I didn't realize that the http path could be different from what they show in the documentation, but I guess I could have inferred from [this image](https://docs.azuredatabricks.net/user-guide/bi/jdbc-odbc-bi.html#http-path) in the Azure docs (I'm guessing you're on Azure? I'm on AWS where the docs are [slightly different](https://docs.databricks.com/user-guide/bi/jdbc-odbc-bi.html#http-path)). Thanks for pointing that out.

Looks like you've made changes to the ``host`` and ``user`` args as well. I would prefer to keep these as they are currently. This is the recommendation by [PEP249](https://www.python.org/dev/peps/pep-0249/#footnotes) which defines the DBAPI 2.0 spec. It's also consistent with other DBAPI libs like psycopg2 and mysql-python.

If you revert the ``host`` and ``user`` changes and fix the signature I'll merge this in. I think you might also need to remove the ``://`` from the ``urlunsplit`` to set the url properly.

**Comment by crflynn** [comment]
Actually, are those digits an Azure account id? Since the path is almost the same except for those digits would it be simpler to include an account_id (default 0) param rather than http_path?

**Comment by gwerbin** [comment]
I suspect they might be (hopefully I didn't accidentally exfiltrate something important!) -- I'll make those changes over the weekend. Plus Black & a full test run.

**Comment by crflynn** [comment]
I think http_path should be fine, actually, so disregard the bit about account_id. This way the package is more or less future proof if Databricks happens to change the path or provide something different on a platform other than AWS/Azure.

**Comment by crflynn** [comment]
@gwerbin are you planning on making these changes? If not I'll handle it myself as I think the compatibility across platforms would be a nice integration here.

**Comment by gwerbin** [comment]
Sorry I never got around to this. Thanks for making the fix :+1:

**Pull request closed without merging**
